# Generated by Django 5.2.8 on 2025-11-29 01:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('meses_pagados', models.PositiveIntegerField(default=1)),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
    ]
